/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.elyograg.changeme;

import org.junit.Test;

public final class MainTests {
  @Test
  final void someTest() {

  }
}
